// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Control.FIO")>]
[<assembly: AssemblyProductAttribute("FSharp.Control.FIO")>]
[<assembly: AssemblyDescriptionAttribute("F# version of Scala's ZIO Environment")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Control.FIO"
    let [<Literal>] AssemblyProduct = "FSharp.Control.FIO"
    let [<Literal>] AssemblyDescription = "F# version of Scala's ZIO Environment"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
